### ISSUE TITLE
Question:  Linux only or Windows too?

### ISSUE THREAD

**Issue by jamfwright** [feexd/pocs#2]
Trying to understand the attack surface.  The details in the announcement on OpenWall indicate Linux was tested and vulnerable.  Anyone know or test to see if Docker on Windows is affected?

**Comment by feexd** [comment]
I believe Docker on Windows runs on a Linux VM using HyperV, so it should work. That said you'll only be able to escape to the underlying VM rather than to the Windows host.

**Comment by jamfwright** [comment]
Thank you for your response, this is helpful!
